name: postgres
version: 13
meta:
  warmup: false
  num_run: 1
  num_thread: 4
  seed: 42
  instance: m5.xlarge
  use_union: [ "avg", "search_sort_head" ]
  use_uber_schema: [ "search_sort_head" ]
benchmark:
  network_log_analytics: [ "avg" ]
  network_log_search: [ "search" , "search_sort_head" ]
#  network_log_analytics: [ "range_sum", "range_sum_no_index" ]
