#!/bin/bash
mkdir ../bulk-format
id=0
for file in *.ndjson
do 
    if test -f "$file"
    then 	    
	IFS=$'\n' # make newlines the only separator
	set -f          # disable globbing
	for line  in $(cat < "$file"); do
	    id=$((id+1))
	    bulkindex='{ "index" : { "_index" : "test", "_type" : "type1", "_id" : "'"$id"'" } }'
            echo "$bulkindex 
$line" >> ../bulk-format/${file%.*}-bulkformat.ndjson
	done
    fi
done 
