kind: search
dataset:
  name: network_log
query:
  random_orig_h:
    field: id.orig_h
    # ignored when trace file is given
    values: ["10.47.3.50", "foo"]
    trace_file: "network_log_search_30.ndjson"
    batch_size: 30
    desc: "search id.orig_h"
