name: mongo
version: 4.2
meta:
  warmup: false
  num_run: 1
  num_thread: 4
  seed: 42
  instance: m5.xlarge
benchmark:
  network_log_analytics: [ "avg" ]
  network_log_search: [ "search" , "search_sort_head" ]
#  network_log_analytics: [ "range_sum" ]
