name: mongo
version: 4.2
meta:
  warmup: false
  num_run: 1
  num_thread: 8
  seed: 42
  instance: m5d.2xlarge
benchmark:
  network_log_analytics: [ "avg" ]
  network_log_search: [ "search" , "search_no_index",
                        "search_sort_head",
                        "search_sort_head_no_index" ]
#  network_log_analytics: [ "range_sum" ]
